Make it better

diff --git a/bin/the_checker b/bin/the_checker
--- a/bin/the_checker
+++ b/bin/the_checker
@@ -5,20 +5,21 @@ TARGET=$1
 TIMEOUT=2
 RECHECKS=5
 HOST="$(basename "${TARGET}")"
-RUNDIR="${XDG_RUNTIME_DIR}/gemini-healthchecker/${HOSTNAME}"
+RUNDIR="${XDG_RUNTIME_DIR}/gemini-healthchecker/${HOST}"
 
 _is_up()        { [[ $(tail -n1 "${RUNDIR}/state") -eq 20 ]]; }
 _is_down()      { ! _is_up; }
 _was_up()       { [[ $(tail -n1 "${RUNDIR}/last_state") -eq 20 ]]; }
 _was_down()     { ! _was_up; }
-_write_state()  { echo "$1" >> "${RUNDIR}/state"; }
 _last_success() { stat -c %Y "${RUNDIR}/last_success"; }
 _print_date()   { date -u --iso-8601=seconds --date="@$1"; }
+_test_target()  { _gemini_status_code >> ${RUNDIR}/state; }
 
-_test_target() {
+_gemini_status_code() {
   echo -e "${TARGET}/\r\n" \
     | timeout ${TIMEOUT} openssl s_client -connect ${HOST}:1965 -ign_eof -quiet 2>/dev/null \
-    | awk '(NR==1) { print $1 }'
+    | awk '(NR==1) {print $1; exit 0}' \
+    || echo 0
 }
 
 mkdir -p "${RUNDIR}"
@@ -27,6 +28,7 @@ if [[ -f "${RUNDIR}/state" ]]; then
 else
   echo 20 > "${RUNDIR}/last_state"  # assume it's ok
 fi
+touch "${RUNDIR}/state"
 
 for ((i=1;i<RECHECKS;i++)); do
   _test_target
@@ -36,7 +38,7 @@ done
 _is_up && touch "${RUNDIR}/last_success"
 
 if _is_up && _was_down; then
-  echo "recovered since failing at $(_print_date "$(_last_success)")"
+  echo "${TARGET} has recovered since failing at $(_print_date "$(_last_success)")"
 elif _is_down && _was_up; then
-  echo failed
+  echo "${TARGET} has entered an alarm state"
 fi
